In [1]:
# Import relevant libraries
import numpy as np

/kaggle/input/consensus-sample/cons_sample.txt


In [15]:
## ERROR IN THIS CODE

# for records in sequence_records_list:
#     for j in range(len(sequence_records_list)):
#         for sequence in records.seq:
#             if sequence[j] == 'A':
#                 profile_matrix[0][j] += 1
#             else:
#                 pass
# print(profile_matrix)

IndexError: string index out of range

The issue in your code arises from how you are iterating over the sequences and positions in the for loop. Specifically, you're trying to update the profile matrix based on the count of 'A's at each position in each sequence, but the loops aren't structured correctly for this task.

Let’s break it down:

**Problem Points:**
1. Wrong Loop Order:
You are using two for loops, one to loop over sequence_records_list and another to loop over the sequences (incorrectly using range(len(sequence_records_list))). This doesn't correctly reference the characters in the sequence for each position.
2. Incorrect Indexing:
Inside the loop, you're iterating over records.seq (each sequence) but then incorrectly reference sequence[j] for positions. You should be using the j index to access the sequence characters.
3. Sequence Processing:
For each sequence, you need to update the profile matrix at the specific position, but your code tries to use both the record and sequence in the same loop, which creates issues.

**Solution:**

You should:

* Loop over each record (records).
* Loop over the positions of each sequence.
* For each position, check if the character is 'A' and update the profile matrix.

# Another Attempt (Slow breakdown of problem)

In [2]:
string1 = 'ATCCAGCT'
string2 = 'GGGCAACT'
string3 = 'ATGGATCT'
length = len(string1)
strings_list = [string1, string2, string3]
print(strings_list)

['ATCCAGCT', 'GGGCAACT', 'ATGGATCT']


In [5]:
sample_matrix = np.zeros((4, length))
# Optionally round the values first if needed
# This ensures any small floating-point inaccuracies are removed
sample_matrix = np.rint(sample_matrix)

# Convert the matrix to integer type
sample_matrix = sample_matrix.astype(int)
#print(sample_matrix)


In [6]:
for string in strings_list:
    for i in range(length):
        if string[i] == 'A':
            sample_matrix[0][i] += 1
        elif string[i] == 'C':
            sample_matrix[1][i] += 1
        elif string[i] == 'G':
            sample_matrix[2][i] += 1
        elif string[i] == 'T':
            sample_matrix[3][i] += 1
print(sample_matrix)

[[2 0 0 0 3 1 0 0]
 [0 0 1 2 0 0 3 0]
 [1 1 2 1 0 1 0 0]
 [0 2 0 0 0 1 0 3]]


**Step 1: Define Labels**
This list, labels, contains labels that correspond to each row in sample_matrix. Each label represents a nucleotide base.

**Step 2: Loop Through sample_matrix with enumerate()**
* Here, enumerate(sample_matrix) iterates over each row in sample_matrix and also provides the row's index.
* i is the index (0, 1, 2, or 3) that corresponds to each row.
* row is the actual data in each row.

Since sample_matrix is a 2D array, enumerate() naturally goes through each row one at a time because rows are the first dimension in a 2D array (i.e., sample_matrix[0] is the first row, sample_matrix[1] is the second row, and so on).

**Step 3: Convert Row Data to a String of Integers**
* map(str, row) converts each integer in row to a string.
* ' '.join(...) combines these string elements into one single string where each element is separated by a space.
So, if row is [1, 0, 2, 3], row_str becomes '1 0 2 3'.

**Step 4: Print the Label and Row Data**
* labels[i] provides the label for the current row based on i (e.g., A: for the first row).
* {row_str} is the formatted row data as a space-separated string.
This print() statement outputs the label followed by the matrix row data.

In [7]:
# Labels for the rows
labels = ['A:', 'C:', 'G:', 'T:']
# Loop through each row and print with the corresponding label
for i, row in enumerate(sample_matrix):
    # Join the row elements as a string of space-separated integers
    row_str = ' '.join(map(str, row))
    
    # Print the label followed by the row
    print(f"{labels[i]} {row_str}")

A: 2 0 0 0 3 1 0 0
C: 0 0 1 2 0 0 3 0
G: 1 1 2 1 0 1 0 0
T: 0 2 0 0 0 1 0 3


In [19]:
# for i in range(length):
#     for string in strings_list:
#         if string[i] == 'A':
#             sample_matrix[0][i] += 1
#         elif string[i] == 'C':
#             sample_matrix[1][i] += 1
#         elif string[i] == 'G':
#             sample_matrix[2][i] += 1
#         elif string[i] == 'T':
#             sample_matrix[3][i] += 1
# print(sample_matrix)

[[2. 0. 0. 0. 3. 1. 0. 0.]
 [0. 0. 1. 2. 0. 0. 3. 0.]
 [1. 1. 2. 1. 0. 1. 0. 0.]
 [0. 2. 0. 0. 0. 1. 0. 3.]]


### Both iterations (looping through strings first, and then through positions, and vice versa) give same results

Both versions of the code give the same result because the logic of how you update the sample_matrix remains the same. Let's break it down and compare the two loops:

**Original Code (String Loop First):**

for string in strings_list:
    for i in range(length):
        if string[i] == 'A':
            sample_matrix[0][i] += 1
        elif string[i] == 'C':
            sample_matrix[1][i] += 1
        elif string[i] == 'G':
            sample_matrix[2][i] += 1
        elif string[i] == 'T':
            sample_matrix[3][i] += 1
            
**Logic:**

* This version loops over each string in strings_list first.
* For each string, it loops over each position i in the string (length of the string).
* It checks which character ('A', 'C', 'G', or 'T') is at position i and updates the corresponding row of the matrix.

**Modified Code (Position Loop First):**

for i in range(length):
    for string in strings_list:
        if string[i] == 'A':
            sample_matrix[0][i] += 1
        elif string[i] == 'C':
            sample_matrix[1][i] += 1
        elif string[i] == 'G':
            sample_matrix[2][i] += 1
        elif string[i] == 'T':
            sample_matrix[3][i] += 1

**Logic:**

* This version loops over each position i first.
* For each position i, it loops over each string in strings_list.
* It checks which character ('A', 'C', 'G', or 'T') is at position i across all strings and updates the matrix in the same way.

**Why Both Work:**
In both versions, you're essentially doing the same thing:

* For each position i in the sequences, you're counting how many 'A's, 'C's, 'G's, and 'T's appear and updating the sample_matrix accordingly.

**The only difference is the order of loops:**

* In the first version, you go through all positions of the first string, then the second string, and so on.
* In the second version, you check all strings at position 0 first, then position 1, and so on.
Both approaches ensure that every nucleotide at every position is checked, leading to the same result in the matrix, even though the loop order is reversed.

**Conclusion:**
* Order of iteration doesn't matter in this case as long as you are processing each character at each position for every string.
* Both versions are correct and will give the same result because they essentially perform the same comparisons and updates.

### Generally the order of iterations matters

This **is** a special case. In general, the order of iteration does matter in most algorithms or loops. The reason it doesn’t matter in your case is because the logic is independent of the order of looping. You're doing the same operation (updating the matrix) for each character at each position, regardless of whether you check by position first or string first.

**Why This is a Special Case:**
1. Commutative Operation: The update operation sample_matrix[row][i] += 1 (incrementing the count for each base) is commutative. This means the result is the same no matter the order in which you count, as long as you eventually count every character at every position. So whether you go through the positions or the strings first, the same counts are updated.

2. No Interdependency: Each string's sequence at a given position is independent of other positions or other strings. You're not relying on previous values or iterations; you’re simply incrementing the matrix based on the character at each position. This lack of dependency between the iterations is what allows the loop order to be interchangeable.

**Cases Where Order Does Matter:**
In many algorithms, the order of iteration does matter. Some examples:

1. <ins>Cumulative or Dependent Operations</ins>: If each step in your loop depends on the results of the previous steps, the order becomes critical. For example:
*     Matrix multiplication: The order of accessing elements matters because you need to compute row by column products, and if the order is wrong, you won’t get the correct result.
* Filling an array based on previous values: If you're filling an array based on the values that have been filled before (e.g., dynamic programming), changing the order can result in incorrect or incomplete updates.
2. <ins>In-place Modifications</ins>: If you're modifying the list or matrix itself during the loop, the order of iteration can change how or when elements are modified. For instance, removing elements while iterating over them in a certain order can lead to skipped elements or incorrect results.
 
3. <ins>Sorting Algorithms</ins>: Sorting is highly order-dependent. A sorting algorithm must follow a strict process to ensure the correct order of elements, and changing how or when elements are compared would result in a completely different (and likely incorrect) sorted list.

4. <ins>Multi-loop algorithms</ins>: Some problems involve nested loops where the inner loop depends on the results of the outer loop. For example, when comparing elements in two different arrays or matrices, switching the order of the loops might cause the wrong comparisons to be made.

**Conclusion:**
Yes, this is a special case where the order of iteration doesn’t matter because each iteration step is independent and the operation is commutative. In most algorithms, though, the order is crucial to getting the right result.

It's great that you're thinking deeply about this, as understanding when iteration order matters is key to writing robust code!

#### Consensus String Generation

In [38]:
# # Accessing each column in a loop
# column_list = []
# for i in range(sample_matrix.shape[1]):
#     column_list.append(sample_matrix[:, i])

In [10]:
#max_in_columns = np.max(sample_matrix, axis=0)
max_in_columns = [max(row[i] for row in sample_matrix) for i in range(len(sample_matrix[0]))]
print(max_in_columns)

[2, 2, 2, 2, 3, 1, 3, 3]


# Sample Problem Given

#### Profile Matrix Generation

In [2]:
pip install biopython

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 35.3 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [3]:
# Import SeqIO to parse FASTA file
from Bio import SeqIO

#Save file path in a variable
filePath = '/kaggle/input/consensus-sample/cons_sample.txt'

#Parse FASTA file to extract sequence records
sequence_records_list = list(SeqIO.parse(filePath, "fasta"))

#Save the length of sequences in a variable
sequences_length = len(sequence_records_list[0].seq)
print(sequences_length)

8


In [8]:
# Create a 2D array with 4 rows and columns = length of sequences, initialized to zero
profile_matrix = np.zeros((4, sequences_length))

# Optionally round the values first if needed
# This ensures any small floating-point inaccuracies are removed
profile_matrix = np.rint(profile_matrix)

# Convert the matrix to integer type
profile_matrix = profile_matrix.astype(int)

print(profile_matrix)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [9]:
sequence_list = []
for record in sequence_records_list:
    sequence_list.append(str(record.seq))

print(sequence_list)

['ATCCAGCT', 'GGGCAACT', 'ATGGATCT', 'AAGCAACC', 'TTGGAACT', 'ATGCCATT', 'ATGGCACT']


In [10]:
def consensus_profile_generator(list_of_sequences, length_of_sequences, matrix):
    for string in list_of_sequences:
        for i in range(length_of_sequences):
            if string[i] == 'A':
                matrix[0][i] += 1
            elif string[i] == 'C':
                matrix[1][i] += 1
            elif string[i] == 'G':
                matrix[2][i] += 1
            elif string[i] == 'T':
                matrix[3][i] += 1
    #return matrix

    # Labels for the rows
    labels = ['A:', 'C:', 'G:', 'T:']

    # Build the consensus string
    consensus_string = ""
    for j in range(matrix.shape[1]):
        # Find the index of the max value in each column
        max_index = np.argmax(matrix[:, j])
        # Append the corresponding base to the consensus string
        consensus_string += labels[max_index][0]

    # Loop through each row and print with the corresponding label
    for i, row in enumerate(matrix):
        # Join the row elements as a string of space-separated integers
        row_str = ' '.join(map(str, row))
        # Print the label followed by the row
        print(f"{labels[i]} {row_str}")
    # Print the consensus string
    print("\nConsensus String:", consensus_string)

In [11]:
consensus_profile_generator(sequence_list, sequences_length, profile_matrix)

A: 5 1 0 0 5 5 0 0
C: 0 0 1 4 2 0 6 1
G: 1 1 6 3 0 1 0 0
T: 1 5 0 0 0 1 1 6

Consensus String: ATGCAACT


## Actual Problem Solution

In [13]:
#Save file path in a variable
filePath2 = '/kaggle/input/rosalind-cons/rosalind_cons.txt'
#Parse FASTA file to extract sequence records
sequence_records_list2 = list(SeqIO.parse(filePath2, "fasta"))

#Save the length of sequences in a variable
sequences_length2 = len(sequence_records_list2[0].seq)
#print(sequences_length2)

# Create a 2D array with 4 rows and columns = length of sequences, initialized to zero
profile_matrix2= np.zeros((4, sequences_length2))

# Optionally round the values first if needed
# This ensures any small floating-point inaccuracies are removed
profile_matrix2 = np.rint(profile_matrix2)

# Convert the matrix to integer type
profile_matrix2 = profile_matrix2.astype(int)

#print(profile_matrix2)

sequence_list2 = []
for record in sequence_records_list2:
    sequence_list2.append(str(record.seq))

print(sequence_list2)

['TGGTGTTCCGGTACTTCCCTTTCTTCCGAGCGTTAATCCATGGGACGTGGTCCGGCGTAGAGGCCGGAAGGAGTTCGATGAGCATTATCTGTCCGCATTTTTGGTGGTTCATCAAGACATTGCAAACGATTTAGCATATAGTCGGGTCTAATATCTTTAAGCTTATTAGACCGGGAGCAGCTATACCGCAATGCCCCGGAGTACCTCAAATAGACCATACTTGCCCCGATTAGACGATTTCGGCCCATAGGTCAGAGTTTACCCCAAGCCGCGCCACCCGACGGGTGTCAAACAGACTGGCAGCGCAGACATTACGGACAGTTATCCTGCTAGATTCGCGAACTATTGCTGCGGCTGCTCTCTGGGCGAGAGAAAATAACGAACTAGTGCGTGCCTCCCCGCCGTCTATTCATAGCGGTACGCATATATCCGGGCTGTATAGGACAACCATATTCTTCCTGTCACGCGATTCATTGTCATGAACCCTTGCTTGGAGGCTGACTTCGTGCAGCAGTGGCCAATCGTTCCGCATAGACGTTCTCAACTCAAATACAGGTGGTTCGTGCTTGAAGTGATAGAGCTTGAAAATCGTCTAGTGACTGATTTGATTGGATATCAATAACCGGTTATCAACGATGCACAGCCGACCTAATCTTGTACAACGGGTGTAATTAGTCAACAGTGCGTTAGGAACCCGATAAGCACCCTCGTAAGTGGTTTATCATAGATGGAAATGTCAATGTCAGGGGCAAGGGTGTCGCTACCATAGAGCAACCAAGGTCTCATAGCCATCAAGAAGGAGGTATTATGCGCAATCATCATTGCTCTACTCTCCGGATTACCTGTGAGCTTCCGCGAGGCATTTGGCGAATGCGCCGGTAGTGACGTGCACGTCCACCGTATATTAGTCCTATGAAC', 'TTGTACTCCAACAGTGACGTCTTGTCTCCTATTGGAGGATTCCAATAGTGTCTCCATATCTCACATCGCACATTTT

In [14]:
consensus_profile_generator(sequence_list2, sequences_length2, profile_matrix2)

A: 0 3 2 2 2 2 1 1 1 1 3 0 3 1 0 1 3 3 2 4 3 0 2 2 2 2 4 2 3 0 3 2 0 1 4 6 7 3 2 3 2 3 1 5 4 3 4 4 2 0 4 0 1 1 2 2 2 4 4 2 3 1 3 1 3 1 3 4 4 4 2 4 1 3 0 1 2 1 1 1 3 0 4 3 1 1 5 1 2 0 5 3 1 3 1 1 2 4 1 4 2 1 4 3 1 1 4 2 4 1 1 3 0 2 2 3 3 2 1 1 3 3 1 3 3 4 2 1 2 3 2 1 4 3 6 2 2 4 1 2 1 2 3 0 2 1 2 1 2 2 4 2 5 3 2 1 3 5 6 4 2 1 2 1 4 3 1 5 2 6 1 2 3 3 3 2 2 1 1 1 3 1 4 0 2 3 2 2 3 2 4 1 2 2 4 2 4 2 2 5 2 1 1 5 3 4 1 4 3 4 3 3 3 4 4 3 1 2 3 2 1 2 2 1 1 1 3 3 2 3 3 2 1 2 3 2 2 0 2 3 2 1 1 2 2 1 3 3 4 2 3 3 4 4 2 1 3 1 1 1 3 3 2 3 2 3 1 3 2 4 6 3 2 2 3 6 0 5 0 4 3 5 0 2 0 0 3 2 2 3 2 1 3 3 2 2 2 3 3 4 3 3 4 1 0 1 2 3 3 1 5 2 2 2 3 3 2 4 2 2 5 3 4 2 1 0 1 4 5 1 4 4 0 2 0 1 2 3 1 0 2 4 3 2 4 1 1 3 5 2 4 0 5 2 2 4 2 4 2 2 3 1 2 1 2 2 2 3 4 2 3 3 5 3 5 2 3 3 2 1 3 3 7 2 2 4 3 4 2 4 2 2 2 2 2 3 3 3 3 3 6 2 1 0 3 0 2 3 1 5 2 3 3 4 1 5 5 3 2 1 0 2 4 2 0 5 2 3 3 1 3 2 3 1 1 5 4 0 2 1 3 4 4 4 2 3 4 1 1 2 2 2 2 2 2 2 2 1 3 3 1 1 1 2 4 3 3 1 1 1 1 1 4 1 3 2 3 1 1 2 1 2 3 2 3 2 2 3 0 2 1 2 2 2 3 3 2 3 3

## Problem Code and its problems

def profile_matrix_generator(list_of_sequences, length_of_sequences, matrix):
    for string in list_of_sequences:
        for i in range(length_of_sequences):
            if string[i] == 'A':
                matrix[0][i] += 1
            elif string[i] == 'C':
                matrix[1][i] += 1
            elif string[i] == 'G':
                matrix[2][i] += 1
            elif string[i] == 'T':
                matrix[3][i] += 1
    #return matrix

    # Labels for the rows
    labels = ['A:', 'C:', 'G:', 'T:']

    # Loop through each row and print with the corresponding label
    for i, row in enumerate(matrix):
        # Join the row elements as a string of space-separated integers
        row_str = ' '.join(map(str, row))
        # Loop through each column to find the maximum value
        for j in range(matrix.shape[1]):
            max_value = max(matrix[:, j])
        # Print the label in the form of a string
        string_base = labels{max_value.index}.rstrip(": ")
        print(string_base)
        # Print the label followed by the row
        print(f"{labels[i]} {row_str}")

Getting the Max Value in Each Column: In the code, you’re looping through each column but only finding the maximum value without determining which base has that maximum count. You’ll need to identify the index of the maximum value in each column, which corresponds to the base (A, C, G, or T).

Accessing Labels for Consensus String: Instead of labels{max_value.index}, you should use indexing with square brackets (labels[max_index]), and for each column, you need to find the base with the highest count.

Constructing the Consensus String: You can build the consensus string by appending the base with the highest count for each column.